refreshItems:
  0:
    location:
      world: world
      x: 0.0
      y: 64.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
    material: DIAMOND_SWORD
    refreshTime: 60
    refreshProbability: 50
  1:
    location:
      world: world
      x: 10.0
      y: 64.0
      z: 10.0
      yaw: 0.0
      pitch: 0.0
    material: DIAMOND_CHESTPLATE
    refreshTime: 120
    refreshProbability: 30
